name: flutter_gaw_cms
description: The admin application for WERKR
publish_to: none
version: 1.4.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.6.0
  tuple: ^2.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  syncfusion_flutter_datepicker: ^29.1.33
  syncfusion_flutter_charts: ^29.1.33
  smooth_page_indicator: ^1.1.0
  carousel_indicator: ^1.0.6
  fl_chart: ^0.66.2
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  beamer: ^1.5.6
  themed: ^5.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.0.0
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.10
  freezed: ^2.4.1
  google_map_polyline_new: ^0.3.0+2
  file_picker: ^10.1.2
  dio: ^5.3.3
  geolocator: ^10.1.0
  widget_to_marker: ^1.0.4
  page_transition: ^2.1.0
  flutter_dropzone: ^4.0.0
  collection: ^1.18.0
  sentry_flutter: ^7.16.1
  flutter_native_splash: ^2.3.2
  flutterwebapp_reload_detector: 0.0.1
  readmore: ^3.0.0
  firebase_core: ^3.13.0
  built_collection: ^5.1.1


  gaw_ui:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_ui
      ref: main
  gaw_api:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_api
      ref: main

dependency_overrides:
  dio: ^5.3.3
  syncfusion_flutter_datepicker: ^29.1.33
  syncfusion_flutter_charts: ^29.1.33
  gaw_ui:
    path: ../flutter_package_gaw_ui
  gaw_api:
    path: ../flutter_package_gaw_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - lib/assets/styles/map_style.json
    - lib/assets/tag_icons/