name: flutter_gaw_cms
description: The admin application for Get-a-Wash
publish_to: none
version: 1.1.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  beamer: ^1.5.6
  themed: ^4.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.10
  freezed: ^2.4.1
  google_maps_flutter: ^2.5.0

  # Get-a-Wash

  flutter_package_gaw_ui:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_ui
      ref: main
  flutter_package_gaw_api:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_api
      ref: main 

# dependency_overrides:
#   flutter_package_gaw_ui: 
#     path: ../flutter_package_gaw_ui
#   flutter_package_gaw_api: 
#     path: ../flutter_package_gaw_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets: 
  
    - assets/translations/