name: flutter_gaw_cms
description: The admin application for Get-a-Wash
publish_to: none
version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  tuple: ^2.0.2

  # Get-a-Wash

  gaw_ui:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_ui
      ref: main
  gaw_api:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_api
      ref: main

dependency_overrides:
  gaw_ui:
    path: ../flutter_package_gaw_ui
  gaw_api:
    path: ../flutter_package_gaw_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true