name: flutter_gaw_cms
description: The admin application for Get-a-Wash
publish_to: none
version: 1.0.0+5

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0
  tuple: ^2.0.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  toggle_switch: ^2.1.0
  syncfusion_flutter_datepicker: ^23.1.36
  syncfusion_flutter_charts: ^23.1.36
  smooth_page_indicator: ^1.1.0
  carousel_indicator: ^1.0.6
  fl_chart: 0.66.0
  image_picker: ^1.0.7
  dotted_border: ^2.1.0
  beamer: ^1.5.6
  themed: ^5.0.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  easy_localization: ^3.0.2
  flutter_riverpod: ^2.3.10
  freezed: ^2.4.1

  # Get-a-Wash

  gaw_ui:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_ui
      ref: main
  gaw_api:
    git:
      url: https://lyte-manager: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@github.com/LYTE-studios/flutter_package_gaw_api
      ref: main

dependency_overrides:
  gaw_ui:
    path: ../flutter_package_gaw_ui
  gaw_api:
    path: ../flutter_package_gaw_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true